### ISSUE TITLE
Crash 1.20 after version correction

### ISSUE THREAD

**Issue by Illest8** [LangYueMc/EquipmentStandard#1]
### Mod loader

Forge

### Modloader version

47.2.0

### Minecraft version

1.20.1

### Mod version

1.1.3

### latest.log

https://gist.github.com/Illest8/d4fb684332ab0493ae265820f53002b9#file-gistfile1-txt

### Issue description

The toml is not set to be compatible for version 1.20.1. You have the range set to (1.20.2, 1.21). Here's the crash issue ^

**Comment by Moirstral** [comment]
Sorry for publishing without testing forge, I only tested fabric, thanks for the feedback.

**Comment by Moirstral** [comment]
Fixed in 1.1.4

**Comment by Illest8** [comment]
Thanks for the response! 1.1.4 fixes the toml but not the crash. The one I posted above is still relevant.

**Comment by Moirstral** [comment]
> Thanks for the response! 1.1.4 fixes the toml but not the crash. The one I posted above is still relevant.

It should be a mod incompatible. When I tested without the other mod, it was normal. Can you give me your mod list?

**Comment by Illest8** [comment]
Mod List:
https://gist.github.com/Illest8/2398f4383c1dc7c41f8da4956ec3dc42

Error:
https://gist.github.com/Illest8/edaaa950606c99f265f90a8b7c06895c

**Comment by Moirstral** [comment]
It should have been fixed. The reason is that the client event is registered on the server side. 
If it is confirmed that it has been fixed, you can close this issue.

**Comment by Illest8** [comment]
Is this a client side mod only? I created a new server and only put the dependencies in the mods folder along with the mod. I keep on getting the error I posted above.

**Comment by Moirstral** [comment]
> Is this a client side mod only? I created a new server and only put the dependencies in the mods folder along with the mod. I keep on getting the error I posted above.

No, it is applicable to both side. Try it with version 1.1.5. It should be fixed. I tested 1.20.2.
