### ISSUE TITLE
Should use ModifyReturnValue for better compatibility

### ISSUE THREAD

**Issue by Karashok-Leo** [LangYueMc/EquipmentStandard#12]
https://github.com/LangYueMc/EquipmentStandard/blob/ea13c18b77f04ae807c9f527e3d2a8d18f3afc27/common/src/main/java/me/langyue/equipmentstandard/mixin/ItemStackMixin.java#L65
will conflict with https://github.com/Karashok-Leo/L2Hostility-Fabricated/blob/master/src/main/java/karashokleo/l2hostility/mixin/ItemStackMixin.java

**Comment by Moirstral** [comment]
thanks for contributing.
