### ISSUE TITLE
1.20.1forge启动不能

### ISSUE THREAD

**Issue by kakukirin** [LangYueMc/EquipmentStandard#3]
### Mod 加载器

Forge

### Mod 加载器版本

47.2.6

### Minecraft 版本

1.20.1

### 本模组版本

1.3.2

### latest.log

[latest.log](https://github.com/LangYueMc/EquipmentStandard/files/13399630/latest.log)

### 详细描述

[latest.log](https://github.com/LangYueMc/EquipmentStandard/files/13399630/latest.log)
[crash-2023-11-18_16.47.15-fml.txt](https://github.com/LangYueMc/EquipmentStandard/files/13399631/crash-2023-11-18_16.47.15-fml.txt)
![image](https://github.com/LangYueMc/EquipmentStandard/assets/111631884/b2b95b4e-2be3-41a7-bc0d-c58b694ecc5b)
![image](https://github.com/LangYueMc/EquipmentStandard/assets/111631884/7d8ba5d4-a6e1-463a-bda8-d6249a1b35e3)

**Comment by Moirstral** [comment]
果然还是出问题了，forge 我有个包下不下来，就没测试。容我慢慢下下来试试

**Comment by Moirstral** [comment]
好了，修复了，等 1.3.3 发布成功后你看下，没问题就关掉吧。

**Comment by kakukirin** [comment]
好的我试试

**Comment by Moirstral** [comment]
forge 需要 1.3.4 才能正常工作。已测试
