### ISSUE TITLE
工具只有幸运属性

### ISSUE THREAD

**Issue by wsxiya** [LangYueMc/EquipmentStandard#4]
### Mod 加载器

Forge

### Mod 加载器版本

forge47.1.3

### Minecraft 版本

1.20.1

### 本模组版本

1.3.6

### latest.log

游戏不会崩溃，武器和盔甲能够获得其他属性

### 详细描述

与“Sinytra Connector”使用加载fabric的mod后工具只有幸运属性，暂时只测试了有3个mod导致工具只有幸运属性，测试的mod有“better nether”，“AdventureZ”，“Bosses of Mass Destruction”，我觉得应该还有更多mod会导致工具只有幸运属性。

**Comment by wsxiya** [comment]
forge47.2.6跟上述情况一样

**Comment by Moirstral** [comment]
你直接用 forge 版本的呢？modrinth 上有 1.3.6 的 forge 的。

**Comment by wsxiya** [comment]
> 你直接用 forge 版本的呢？modrinth 上有 1.3.6 的 forge 的。

用的是昨天更新的1.3.6forge版本的

**Comment by Moirstral** [comment]
那就换 fabric 版本的

**Comment by wsxiya** [comment]
> 那就换 fabric 版本的
fabric好像不兼容Sinytra Connector吧

**Comment by wsxiya** [comment]
> 那就换 fabric 版本的

刚刚试了一下，fabric兼容Sinytra Connector，但是跟forge一样，稿子和斧只有幸运属性

**Comment by Moirstral** [comment]
用最新 fabric 版再试下

**Comment by wsxiya** [comment]
> 用最新 fabric 版再试下

我用最新的forge版本试了下一切正常，貌似没什么问题了
