### ISSUE TITLE
向后移植

### ISSUE THREAD

**Issue by QianFuv** [LangYueMc/EquipmentStandard#6]
### Mod 加载器

Forge

### Mod 加载器版本

43.3.5

### Minecraft 版本

1.19.2

### 本模组版本

*

### latest.log

*

### 详细描述

目前低版本没有很优质的类似模组，希望可以向后移植

**Comment by Moirstral** [comment]
移植挺麻烦的，后面再说吧，现在还有个进度系统没做，做完了基本上不会加新功能了，就向下移植。

**Comment by QianFuv** [comment]
好的 期待

**Comment by QianFuv** [comment]
何时重新捡起这个项目呢 :(

**Comment by Moirstral** [comment]
> 何时重新捡起这个项目呢 :(

按我以往的周期，这可能得年底了。

**Comment by QianFuv** [comment]
年底嘛 沃趣 没事没事 我就耐心等待吧awa
