### ISSUE TITLE
About weapon rarity and attribute values and upgrades |  武器のレアリティと属性値、アップグレードについて

### ISSUE THREAD

**Issue by CanecaKun** [LangYueMc/EquipmentStandard#7]
### Mod loader

Forge

### Modloader version

forge-1.20.1-47.2.0

### Minecraft version

1.20.1

### Mod version

EquipmentStandard-1.4.2+mc1.20-forge

### Modpack

Too many mods, also custom modpack but no compat issue so i don´t think its relevant here

### latest.log

- no log needed, also don´t think its possible to, since its ingame -

### Issue description

I just want to know if there is a way to config so we get better attributes on unique weapons/armor, and maybe if there  will be a way to increase stats aside from rerolling, more expensive if needed, but possible.

Sorry for creating an issue here on github but i saw no other way of contact.

Thanks for your time!

**Comment by CanecaKun** [comment]
Also, maybe english wiki? I have no idea how most attributes work tbh

**Comment by CanecaKun** [comment]
To complement my previous comment, unique gear is still better if compared to legendary ones most of the time, but i don´t feel like its good enough, if taken into account how rare unique weapons are, the stats do not really give a noticeable change in DPS/Protection, just my opinion of course.

And something else i don´t know if its a bug, but when upgrading armor from diamond to netherite or from netherite to modded upgrades like the ones from "deeper and darker mod" or  from "mythic upgrades" only the base stats increase, so your mod does not interact with weapon upgrades from what i witnessed, i think there should be some way to increase stats when upgrading gear or to just increase the stats at any point in time, like how i mentioned in the initial post comment,  so at least we can grind for increased crit damage/chance which is the classic "chase" for RPG players, after all its all about increasing the numbers, and it would be great to have an actual way of "upgrade" and not just expensive rerolls.
(Also btw i think rerolling from unique to epic should not be a thing, maybe keep the tier and change stats, and changing tier only by upgrading) 

Example: (from netherite to modded upgrade "mythic upgrades" mod)
![image](https://github.com/LangYueMc/EquipmentStandard/assets/62015531/7918a5f8-e947-47ac-9776-2ca9683eb830)


An item/method to increase certain stats or increase weapon rarity  from epic->legendary->unique
I honestly think that a nether star or something that needs netherite would  not be bad, since reroll already uses nether stars and since the hunt for perfect stats its mostly a late game thing.

Also, could you maybe make an english wiki? I have no idea how most attributes work to be honest, the few english/japanese stuff on the github page is not clear. A downloadable datapack with all possible stats would be great too.

**Comment by CanecaKun** [comment]
I also found issues with farmer's delight knives and modded/vanilla axes getting dig speed as a status instead of offensive stats, your mod probably recognises them as tools and not weapons (which they kind of are, but they're still good in combat and dig speed is useless on the knives since they insta break the only block they interact with already) this probably prevents them from getting crit related stats.
IDK if its possible to change them to melee weapon on a datapack, i really don´t know how the format should be so help would be welcome.

**Comment by CanecaKun** [comment]
Hello Mr Mod Developer, are you still with us?

**Comment by CanecaKun** [comment]
Mr Developer, are you still with us or have you been isekai'd? @LangYueMc

**Comment by Moirstral** [comment]
很抱歉现在才回复，前段时间确实比较忙。
Wiki 有英文版本的，是谷歌翻译，我个人能力有限。
所有属性的配置都是通过数据包方式加载的，你的问题是因为我内置的数据包并不合理，所有的属性都是范围内完全随机的，是会出现高稀有度装备属性甚至不如低稀有度的，主要是因为幸运的分值太高，会直接拉高装备分，但是属性分值也是支持数据包配置的，你可以自行修改。当然，也是支持针对某个装备单独配置模板的。一切都在 WIKI 里有说明。

Google翻訳なので正確でない場合はご容赦ください。

少し前までとても忙しかったので、今になって返信して申し訳ありません。
Wiki には英語版があり、それを Google が翻訳しました。私の個人的な能力には限界があります。
すべての属性設定はデータ パッケージを通じてロードされます。問題は、私の組み込みデータ パッケージが不合理であるためです。範囲内で、低レアリティにも劣る属性を持つ高レアリティの装備が存在することになります。主な理由は、ラッキースコアが高すぎるため、装備スコアが直接増加します。ただし、属性スコアはデータパッケージの構成も​​サポートしており、自分で変更できます。もちろん、特定の機器に対して個別にテンプレートを設定することもサポートしています。すべてWIKIで説明されています。

[CHANGELOG_EN.md](https://github.com/LangYueMc/EquipmentStandard/blob/master/CHANGELOG_en.md)

**Comment by CanecaKun** [comment]
And what about being able to upgrade attributes instead of only rerolling, will it be a feature in the future?

I'd be glad to help with translation even though my main language is not English either, and i changed the tittle for Japanese on google translate as well

**Comment by Moirstral** [comment]
所以你的母语是葡萄牙语（通过你截图看到的）？我以为是日语，抱歉了，我是中国人，看你标题是日语，以为你是日本人。
这个mod是我之前工作不忙的时候写的，现在没有精力继续维护，所以不会有新功能了，当然欢迎你的翻译工作。

---

So your native language is Portuguese (as I can see from your screenshot)? I thought it was Japanese, sorry. I'm Chinese, and I thought you were Japanese because of the Japanese title.

This mod was written when I wasn't busy with work, but now I don't have the energy to keep maintaining it, so there won't be any new features. Of course, your translation work is welcome. 

---

Então sua língua nativa é português (como posso ver na sua captura de tela)? Pensei que fosse japonês, desculpe. Sou chinês e achei que você era japonês por causa do título em japonês.

Este mod foi escrito quando não estava ocupado com o trabalho, mas agora não tenho energia para continuar a mantê-lo, então não haverá novos recursos. Claro, seu trabalho de tradução é bem-vindo.

**Comment by CanecaKun** [comment]
Yes, my main language is indeed portuguese, i mistakenly assumed your language was japanese and tried to translate the text so (in my head) you would be more willing to read it, i apologise for that.

Please, in the future if you see an opportunity, make an update on this mod, its ok to leave it aside because of lack of time / energy, but please don't abandon it, i can't code complex stuff like that and nobody else seems interested in doing so.

Thank you for your time, best wishes.
